### ISSUE TITLE
How to catch the response object?

### ISSUE THREAD

**Issue by diegoaguilar** [request/request-promise-native#12]
It seems like right now I can do:

```
  request(someUrl)
  .then(body => {
    // Do something with your body
  })
```

Where can I handle the response object? I need to access headers, status code, etc

**Comment by analog-nico** [comment]
Hi @diegoaguilar , please have a look at the documentation for `request-promise` which includes an [example using the `resolveWithFullResponse` option](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body).

**Comment by robertmain** [comment]
I take it that it's not possible to do the following, then?

```js
const response = await request.post({
        url: 'http://api.me.com',
        resolveWithFullResponse: true,
        form: {
            foo: 'bar',
        }
    });
```

**Comment by JhinDeng** [comment]
what about always return the response, it seems a good practice. make the return with the same type

**Comment by diegoaguilar** [comment]
@robertmain long time since I don't use this lib, but why?
