### ISSUE TITLE
'Cannot find lodash/isFunction'

### ISSUE THREAD

**Issue by carlylumel** [request/request-promise-native#18]
Hi, 

On build my app throws the error `cannot find module lodash/isFunction`, tracing back to request-promise-native. I've tried deleting my node modules folder and reinstalling everything. Does this sound like an inherent error or should I attempt a different fix? 

Thanks.

**Comment by analog-nico** [comment]
It’s hard to say with the available information what caused this issue but the module is part of the `lodash` library that gets installed automatically. So most likely this is an issue with the build environment.
