### ISSUE TITLE
UnhandledPromiseRejectionWarning when using with Request

### ISSUE THREAD

**Issue by horaceli** [request/request-promise-native#19]
Using the original `request` library to make HTTP calls and handle errors. Generally works fine.

However if I import `request-promise-native`, even if it's not used, it'll cause `UnhandledPromiseRejectionWarning` - seems to be interfering with my API calls made with `request`.  Requiring `request-promise` (Bluebird) does not cause this issue - Node GC only catches native promises.

Using Node 8.10.0 LTS.

Can be reproduced with below
```javascript
const request = require('request');
require('request-promise-native');

const main = async () => new Promise((resolve, reject) => {
    request.get({url: `http://google.com/non-existent`})
        .on('response', async response => {
            if (response.statusCode !== 200) {
                return reject({
                    statusCode: response.statusCode
                });
            }
            resolve();
        })
});


test('test 404', async () => {
    expect.assertions(1);
    try {
        await main();
    } catch (e) {
        expect(e.statusCode).toBe(404);
    }
});
```
package.json 
```json
{
  "dependencies": {
    "request": "^2.85.0",
    "request-promise-native": "^1.0.5"
  },
  "devDependencies": {
    "jest": "^22.4.3"
  }
}
```

**Comment by mckenzieja** [comment]
Dont you need to place "await" before your "new Promise"?

**Comment by horaceli** [comment]
Good spot.

I've moved off that project now, going to close this thread.
