### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by dcsan** [request/request-promise-native#2]
getting this error below on a clean app with no other packages...

```
[~/dev/rikai/provisioning]$ npm install                                                                                      *[master] 
provisioning@1.0.0 /Users/dc/dev/rikai/provisioning
├── UNMET PEER DEPENDENCY request@^2.34
└─┬ request-promise-native@1.0.3 
  ├── UNMET PEER DEPENDENCY request@^2.34
  ├─┬ request-promise-core@1.1.1 
  │ └── lodash@4.15.0 
  └── stealthy-require@1.0.0 

npm WARN request-promise-native@1.0.3 requires a peer of request@^2.34 but none was installed.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.
npm WARN provisioning@1.0.0 No description
[~/dev/rikai/provisioning]$ cat package.json                                                                                 *[master] 
{
  "name": "provisioning",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dcsan/provisioning.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/dcsan/provisioning/issues"
  },
  "homepage": "https://github.com/dcsan/provisioning#readme",
  "dependencies": {
    "request-promise-native": "^1.0.3"
  }
}
```

**Comment by dcsan** [comment]
oops! RTFM.

**Comment by analog-nico** [comment]
No problem. 👍

**Comment by meshko** [comment]
Uh can you add reference to RTFM where this is explained?

**Comment by analog-nico** [comment]
@meshko Just read the [Installation section](https://github.com/request/request-promise-native#installation) in the README. You probably forgot to `npm install request` beforehand.

**Comment by meshko** [comment]
Uh, no, unfortunately I do have request installed.  I was trying to get these installed globally, no luck.  Seems to be ok in my local node_modules though.

**Comment by analog-nico** [comment]
@meshko Mmh, can you give me your error output? Maybe I can spot something.

**Comment by meshko** [comment]
```
16:01:41 mkruk@laptop ~/tmp/node> npm install -g request-promise
/usr/local/lib
├── UNMET PEER DEPENDENCY request@^2.34
└─┬ request-promise@4.2.1
  └── UNMET PEER DEPENDENCY request@^2.34

npm WARN request-promise@4.2.1 requires a peer of request@^2.34 but none was installed.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.

```


> 16:02:46 mkruk@laptop ~/tmp/node> npm -g list | grep request
> │ ├─┬ request@2.79.0
> ├─┬ request@2.34.0

**Comment by analog-nico** [comment]
I think the issue is that `request` is not installed at the top level. Make sure `request` is listed in the dependencies of your package.json and the do a clean install.

**Comment by jpuk** [comment]
I have the same issue trying to install globally.

The issue seems to be the request module I have is 2.81 and request-promise is requiring 2.34.

Any idea how to get round this?

**Comment by adamk33n3r** [comment]
@jpuk still getting this two years later...any idea?

**Comment by kemaric** [comment]
I'm having the same issue as well. @dcsan did you actually manage to "solve" the issue?

**Comment by hounaine** [comment]
same here... 
npm WARN request-promise@4.2.5 requires a peer of request@^2.34 but none is installed.
