### ISSUE TITLE
I did not find the localAdress attribute in the native HTTP module.

### ISSUE THREAD

**Issue by LiuWeiMr** [request/request-promise-native#20]
const http = require('http');
const options = {
    host: 'nodejs.cn',
};
const req = http.get(options);
req.end();
req.once('response', (res) => {
    const ip = req.socket.localAddress;
const port = req.socket.localPort;
console.log(`你的IP地址是 ${ip}，你的源端口是 ${port}。`);
// consume response object
});

In native HTTP module, req.socket.localAddress can get the IP used by the current connection of the machine, but this attribute is not found in your module.

**Comment by analog-nico** [comment]
I don’t see `request-promise-native` involved here. Please find a more appropriate place to ask your question. Thanks.
