### ISSUE TITLE
"Attempted to add script that was already added"

### ISSUE THREAD

**Issue by Sora2455** [request/request-promise-native#21]
I am receiving the following error message when trying to run MathJax-Node-Sre (which includes this package):

`Attempting to add script that was already added
[path-to-node_modules]/node_modules/tough_cookie/lib/cookie.js`

I have determined that it is this package that is causing the problem by deleting the likely culprits until I received runtime errors instead of build errors.

In particular, I think it is this line in rp.js:
```JavaScript
// Load Request freshly - so that users can require an unaltered request instance!
var request = stealthyRequire(require.cache, function () {
    return require('request');
},
function () {
    require('tough-cookie');
}, module);
```
Somehow, tough-cookie is being required twice. Is anybody else having this issue?

**Comment by Sora2455** [comment]
In case it matters, I am using a fresh install of mathJax-node-sre (version 3.0.0) which is dependent on jsdom (version 11.11.0) which is dependent on request-promise-native (version 1.0.5).

**Comment by analog-nico** [comment]
The `require('tough-cookie')` call in the snippet above actually serves as a way to not require this library twice. Do you have some further insight about your issue?

**Comment by Sora2455** [comment]
Updating my dependencies and rebuilding seems to have fixed this issue somewhere along the way. Sorry for leaving this open!

**Comment by analog-nico** [comment]
No problem buddy. Thanks for the info!
