### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by vasan93th** [request/request-promise-native#22]
I am using DialogFlow(previously Api.ai) and creating webhooks to make service calls.I am using the `request-promise-native` library to make HTTP Post request.When i executed the code locally in my workstation,it worked great.So i used the same code in DialogFlow inline editor .First it prompted me to add `request` as a dependency.After adding it,I'm getting this error

`The deployment of your Cloud Function failed:
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Cannot read property 'prototype' of undefined
at module.exports (/user_code/node_modules/request-promise-native/node_modules/request-promise-core/configure/request2.js:34:47)
at Object.<anonymous> (/user_code/node_modules/request-promise-native/lib/rp.js:15:1)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/user_code/index.js:10:10)`

My local workstation node js version is v9.11.1 .I tried specifying the same version in DialogFlow package.json 's Node JS version.Here's my `package.json`

`{
  "name": "dialogflowFirebaseFulfillment",
  "description": "This is the default fulfillment for a Dialogflow agents using Cloud Functions for Firebase",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": "v9.11.1"
  },
  "scripts": {
    "start": "firebase serve --only functions:dialogflowFirebaseFulfillment",
    "deploy": "firebase deploy --only functions:dialogflowFirebaseFulfillment"
  },
  "dependencies": {
    "actions-on-google": "2.0.0-alpha.4",
    "firebase-admin": "^4.2.1",
    "firebase-functions": "^0.5.7",
    "dialogflow": "^0.1.0",
    "dialogflow-fulfillment": "0.3.0-beta.3",
    "request-promise-native":"v1.0.5",
    "request":"^1.0.5",
    "async":"2.6.1"
  }
}`

But still no luck.Any help would be very deeply appreciated.I really need this module to work in my dialogflow.

**Comment by analog-nico** [comment]
This pretty much points to not having installed the `request` library. It is a peer dependency that you have to install yourself in addition to `request-promise-native`.
