### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by baoduy** [request/request-promise-native#24]
Hi Team,
Request is very useful library that have a thousand dependence on npm. Thanks for your work hard and keep the library up to date.

I saw sine v1.0.4 the library started using psl that grew the size of this library from 6.1 kb to 140.1 kb. Could you share the reason? Sorry just a curious question.

here is the chart https://bundlephobia.com/result?p=request-promise-native

**Comment by analog-nico** [comment]
Well, I have a hard time to make sense of why bundlephobia shows it like this. `request-promise-native` does not use `pxl` actually. However, the libraries it depends on started using `pxl`. Namely `request@2.88.0` and `tough-cookie@2.4.2`. But both libraries actually shrunk in size when they switched over to `pxl`.

Thus I assume that this is an artifact of bundlephobia.
