### ISSUE TITLE
Any access to response object?

### ISSUE THREAD

**Issue by mattcodez** [request/request-promise-native#3]
The request library shows the callback as `function (error, response, body) `, I figured the error parameter would only show up in the `catch(err)` handler but it appears only `body` is passed in for the `then()` handler.

**Comment by analog-nico** [comment]
Check out the [`resolveWithFullResponse` option](https://github.com/request/request-promise#get-the-full-response-instead-of-just-the-body). Does it solve your issue?

**Comment by mattcodez** [comment]
Yes, I didn't think to look at the upstream documentation, thanks.

**Comment by analog-nico** [comment]
Alright, no problem. Have a good one!

**Comment by shennan** [comment]
Note that for anybody trying to make a post request with json; this seems to work:

```
request.post('http://some-site.com/endpoint', {
    resolveWithFullResponse: true,
    json: {
        /* ... */
    }
})
```
