### ISSUE TITLE
Cannot install on node 6

### ISSUE THREAD

**Issue by m4recek** [request/request-promise-native#35]
request-promise-native cannot be installed on Node 6 due to this issue in `tough-cookie`  https://github.com/salesforce/tough-cookie/issues/140

Seems like they are still solving it, but did not release the package with a fix yet. 

Solution will be to downgrade dependency to `tough-cookie:2.5.0` until the issue with 3.0.0 release is resolved.

**Comment by analog-nico** [comment]
Since this references issue is closed I assume we can close this one as well.
