### ISSUE TITLE
request.cancel() is not a function

### ISSUE THREAD

**Issue by joetidee** [request/request-promise-native#37]
I have the following code:
```
const rq = require("request-promise-native");
rq('https://www.google.co.uk').cancel();
```
but i get:

> TypeError: rq(...).cancel is not a function

**Comment by analog-nico** [comment]
This is a [Bluebird specific feature](https://github.com/request/request-promise#cancel). In order to use it please use [`request-promise`](https://www.npmjs.com/package/request-promise) instead.
