### ISSUE TITLE
Request acts like Promise but not returning an actual Promise

### ISSUE THREAD

**Issue by tiger31** [request/request-promise-native#42]
* Node.js - 8.11.4
* npm - 6.9.0
* request-promise-native : ^1.0.7

``` request(/*url*/) ``` Has ```then``` and ```catch``` blocks but it's not an actual ```Promise``` instance. It returns ```Request```.

Node.js log:

```bash
> const rq = require("request-promise-native")
undefined
> const axios = require('axios')
undefined
> (rq("https://google.com") instanceof Promise)
false
> (rq("https://google.com").then() instanceof Promise)
true
> (axios("https://google.com") instanceof Promise)
true
```

**Comment by analog-nico** [comment]
Please use [`rq(...).promise()`](https://github.com/request/request-promise#promise---for-advanced-use-cases) to get the actual `Promise`.

**Comment by tiger31** [comment]
Thanks, didn't find this one in docs
