### ISSUE TITLE
Security vulnerability in Lodash (Update to version 4.17.12 or later)

### ISSUE THREAD

**Issue by aw-davidson** [request/request-promise-native#49]
Prototype pollution vulnerability found on 2019-07-15

**Comment by mercmobily** [comment]
Can you please update to the latest lodash? The one you are using is vulnerable, and _every_ package using your request-promise-native suffers from it. Thanks

**Comment by analog-nico** [comment]
I am in the process of updating `lodash` via `request-promise-core`. The next version of `request-promise-native` will have this fixed.
