### ISSUE TITLE
 Automatically stringifying the body to JSON in POST operations

### ISSUE THREAD

**Issue by alfdocimo** [request/request-promise-native#51]
Hi there!

I've been using this library for node microservices and found out something that I didn't quite understand the other day. Through looking at the docs of [request-promise](https://github.com/request/request-promise) I realized that you can specify that the response of a POST operation to be automatically stringify

```js
var options = {
    method: 'POST',
    uri: 'http://api.posttestserver.com/post',
    body: {
        some: 'payload'
    },
    json: true // Automatically stringifies the body to JSON
};
```

However, I don't think that is currently supported for _request-promise-native_. Is that right? Would it be good to have support for that?

Thank you! 😄

**Comment by analog-nico** [comment]
It is supported actually. But it does two more things in addition to parsing the response which might be the reason why it exerted a behavior that you didn’t expect. See the description in the [`request` options documentation](https://github.com/request/request#requestoptions-callback). I hope this helps!
