### ISSUE TITLE
'request' is now deprecated.

### ISSUE THREAD

**Issue by shisama** [request/request-promise-native#57]
[request](https://github.com/request/request) has been deprecated since Feb 11th 2020.
Do you have any plan to deprecate this package?

**Comment by analog-nico** [comment]
Yes. Since `request-promise-native` is just a wrapper around `request`, it basically has the same fate. Let me know if you have any further questions about it.

**Comment by shisama** [comment]
Thank you for your comment. I think it's better to show this is deprecated on README like 'request'. If you agree withe me, I will send PR.

**Comment by shisama** [comment]
@analog-nico Thank you for your comment. I think it's better to show this is deprecated on README like 'request'. If you agree withe me, I will send PR.

**Comment by analog-nico** [comment]
That would be great. Thank you @shisama !

**Comment by shisama** [comment]
@analog-nico Thank you. I created the PR(#58).

**Comment by analog-nico** [comment]
@shisama Thanks again. Have a great weekend!
