### ISSUE TITLE
Transform Error ?

### ISSUE THREAD

**Issue by Pascal66** [request/request-promise-native#7]
What does that mean ?

TransformError: RangeError: Maximum call stack size exceeded

**Comment by analog-nico** [comment]
It's a TransformError. So your request succeeded but then an error was thrown while executing your transform function.

The error thrown within your transform function is: "RangeError: Maximum call stack size exceeded".

Does this answer your question?

**Comment by Pascal66** [comment]
Resolved, my fault...
I've made a recursive call between the transform ,and .then
Thank you !

**Comment by analog-nico** [comment]
Alright. Happy coding!
