### ISSUE TITLE
Request Hangs When Setting Body

### ISSUE THREAD

**Issue by HeavyStorm** [request/request-promise-native#9]
Request Version:
    "request": "^2.81.0",
    "request-promise-native": "^1.0.3",

Node Version: 7.8.0

During a Unit Test, I'm using `request-promise-native` to activate a server method that I'm developing. The request is performed as below:

	it("should return 400 when the body doesn't comply with the schema", () => {
		let options: request.RequestPromiseOptions = {
			method: "POST",
			resolveWithFullResponse: true,
			// body: { error: "invalid body" },
			json: true,
		};

		return request("http://localhost:9999/mockpost", options).should.eventually.have.property("statusCode", 400);
	});

If I uncomment the `body` line, the test times out. I've debugged the lib and stepped into the code, but couldn't find the issue - certainly isn't something as simple as stringifying the body.

One thing of note is that the same node process is hosting the server and the client, which may be causing the mess. (of course, `request`'s own tests does that without any problem).

**Comment by analog-nico** [comment]
Hey @HeavyStorm , this is a difficult question since I can’t debug it myself.

Are you able to debug/monitor your server to see if it actually responds in time? If you can answer that you’ll know if the issue is that the server doesn’t respond or the client doesn’t handle the response properly. Let me know what you find out.

**Comment by HeavyStorm** [comment]
@analog-nico I messed up, it was a server side problem. It did concern the body but I only found out after a few attempts. *ashamed*

Thanks for answering so quickly!

**Comment by analog-nico** [comment]
No problem buddy. I am glad you found the cause!
